name: Run Tests and Check Coverage

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r requirements_test.txt

    - name: Run tests with coverage
      run: |
        PYTHONPATH=. pytest --cov=./ --cov-fail-under=95

    - name: Upload coverage report
      if: always()
      run: |
        coveralls
